#!/usr/bin/perl
use v5.010;

#Q)Write a program that computes the circumference of a circle with a radius of 12.5. Circumference is 2π times the radius (approximately 2 times 3.141592654).The answer you get should be about 78.5.
sub f
{
say "Please enter the radius";
chomp($r=<STDIN>);
if ( $r==$r )
{
if ( $r >= 0 )
{
my $circum= 2*22/7*$r;
say "Circumference of circle is - $circum";
}
else
{
say "You have entered nagative value please enter a positive value";
f();
}
}
else
{
say "you have entered a character string, please enter a number";
}
}
f();
