#!/usr/bin/perl
use v5.010;

#Q)Write a program that computes the circumference of a circle with a radius of 12.5. Circumference is 2π times the radius (approximately 2 times 3.141592654).The answer you get should be about 78.5.

my $r=12.5;
my $circum= 2*22/7*$r;
say $circum;

