#!/usr/bin/perl
use strict;
use warnings;

    my $directory = $ARGV[0]; 
    print $directory;
    opendir (DIR, $directory) or die $!;
while (my $file = readdir(DIR)) {

        print "$file\n";

    }

